### ISSUE TITLE
Clean up date

### ISSUE THREAD

**Issue by mtliendo** [qccoders/slack-meetup-slash#3]
Currently, the date will display an event by using the following format: "05 Monday".  It would be great if this was a little more inviting.  This project is using [date-fns](https://date-fns.org/) to format dates.

**Comment by mtliendo** [comment]
#5

**Comment by lsurasani** [comment]
Hi! Could I take a look at this issue?

**Comment by mtliendo** [comment]
@lsurasani sure thing! The project is under heavy development since its first release last week, thank you for your willingness to contribute.
