### ISSUE TITLE
Date/Time displays incorrectly

### ISSUE THREAD

**Issue by brianhankins** [qccoders/slack-meetup-slash#5]
Currently the date / time does not display correctly. See image below.

![image](https://user-images.githubusercontent.com/15353420/39935759-b0ad5d3c-550f-11e8-8b1b-72483b4581b2.png)

Fix:
The second line should be more readable and output the correct date. 

Example:
Date / Time : Monday May 14, 2018 @ 12pm

**Comment by mtliendo** [comment]
05 Monday appears to be the correct date.  The line is question is: https://github.com/qccoders/slack-meetup-slash/blob/master/services/meetup.js#L13 in which it's month-day format.

**Comment by jpdillingham** [comment]
Let's track this in #3 .  Thanks Brian!
